import glyphs from '@/components/topic-artwork.json';
import type { matchInterestCatalog } from './interests';

export type TopicIconName = keyof typeof glyphs;

/** Explicit artwork for every catalog entry; additions must choose an icon. */
export const topicIconMap = {
  "Music": "music",
  "K-pop": "headphones",
  "Hip-hop": "headphones",
  "Pop": "headphones",
  "Rock": "guitar",
  "Afrobeats": "headphones",
  "R&B": "headphones",
  "Jazz": "piano",
  "Classical music": "piano",
  "Indie music": "guitar",
  "Electronic music": "headphones",
  "House music": "headphones",
  "Techno": "headphones",
  "Country music": "guitar",
  "Reggae": "guitar",
  "Latin music": "music",
  "Metal": "guitar",
  "Punk": "guitar",
  "Soul music": "music",
  "Funk": "music",
  "Live music": "music",
  "Music festivals": "ticket",
  "Vinyl records": "disc-3",
  "Karaoke": "mic-vocal",
  "Songwriting": "notebook-pen",
  "Movies": "clapperboard",
  "TV series": "tv",
  "Anime": "venetian-mask",
  "Documentaries": "clapperboard",
  "Comedies": "laugh",
  "Romantic comedies": "book-heart",
  "Horror movies": "ghost",
  "Science fiction": "rocket",
  "Fantasy films": "clapperboard",
  "Action movies": "clapperboard",
  "Thrillers": "clapperboard",
  "Independent films": "clapperboard",
  "Classic cinema": "clapperboard",
  "Foreign films": "clapperboard",
  "Animation": "venetian-mask",
  "Reality TV": "tv",
  "Crime shows": "tv",
  "Sitcoms": "tv",
  "Period dramas": "clapperboard",
  "Superhero movies": "rocket",
  "Film photography": "camera",
  "Movie nights": "popcorn",
  "Film festivals": "ticket",
  "Screenwriting": "notebook-pen",
  "Cinema history": "landmark",
  "Gaming": "gamepad-2",
  "PC gaming": "gamepad-2",
  "Console gaming": "gamepad-2",
  "Mobile gaming": "gamepad-2",
  "Indie games": "gamepad-2",
  "Retro gaming": "joystick",
  "Board games": "dices",
  "Card games": "dices",
  "Chess": "chess-knight",
  "Dungeons & Dragons": "swords",
  "Role-playing games": "swords",
  "Strategy games": "gamepad-2",
  "Cozy games": "gamepad-2",
  "Racing games": "car",
  "Sports games": "gamepad-2",
  "Puzzle games": "puzzle",
  "Escape rooms": "puzzle",
  "Trivia nights": "dices",
  "Esports": "headset",
  "Game development": "code-xml",
  "Virtual reality": "headset",
  "Tabletop games": "dices",
  "Arcade games": "joystick",
  "Pok\u00e9mon": "gamepad-2",
  "Fantasy worlds": "swords",
  "Books": "book-open",
  "Fiction": "book-open",
  "Nonfiction": "book-open",
  "Fantasy books": "book-open",
  "Science fiction books": "book-open",
  "Mystery novels": "book-open",
  "Romance novels": "book-heart",
  "Historical fiction": "landmark",
  "Poetry": "feather",
  "Comics": "book-image",
  "Manga": "book-image",
  "Graphic novels": "book-image",
  "Audiobooks": "book-headphones",
  "Book clubs": "library",
  "Creative writing": "notebook-pen",
  "Journaling": "notebook-pen",
  "Blogging": "notebook-pen",
  "Short stories": "feather",
  "Memoirs": "feather",
  "Philosophy books": "book-open",
  "Psychology books": "brain",
  "Biographies": "book-open",
  "Literary fiction": "book-open",
  "Spoken word": "mic-vocal",
  "Libraries": "library",
  "Art": "palette",
  "Drawing": "pencil-ruler",
  "Painting": "brush",
  "Watercolor": "brush",
  "Illustration": "pencil-ruler",
  "Digital art": "palette",
  "Graphic design": "pencil-ruler",
  "Product design": "pencil-ruler",
  "Interior design": "drafting-compass",
  "Architecture": "drafting-compass",
  "Ceramics": "amphora",
  "Pottery": "amphora",
  "Sculpture": "amphora",
  "Woodworking": "hammer",
  "Calligraphy": "pen-tool",
  "Hand lettering": "pen-tool",
  "Photography": "camera",
  "Street photography": "camera",
  "Portrait photography": "camera",
  "Fashion photography": "camera",
  "Filmmaking": "video",
  "Video editing": "video",
  "Memes": "laugh",
  "Collage": "palette",
  "Museum visits": "landmark",
  "Food & cooking": "chef-hat",
  "Baking": "cake-slice",
  "Coffee": "coffee",
  "Tea": "coffee",
  "Wine tasting": "wine",
  "Craft beer": "beer",
  "Cocktails": "martini",
  "Mocktails": "utensils",
  "Italian food": "pizza",
  "Japanese food": "soup",
  "Korean food": "soup",
  "Indian food": "utensils",
  "Mexican food": "utensils",
  "Thai food": "soup",
  "Mediterranean food": "utensils",
  "Vegan cooking": "salad",
  "Vegetarian food": "salad",
  "Street food": "utensils",
  "Fine dining": "utensils",
  "Brunch": "egg-fried",
  "BBQ": "flame",
  "Desserts": "cake-slice",
  "Chocolate": "candy",
  "Food markets": "store",
  "Trying new restaurants": "store",
  "Travel": "plane",
  "Weekend trips": "plane",
  "Backpacking": "backpack",
  "Road trips": "car",
  "Solo travel": "plane",
  "Luxury travel": "plane",
  "Budget travel": "plane",
  "Train travel": "train-front",
  "Van life": "caravan",
  "City breaks": "building-2",
  "Beach holidays": "tree-palm",
  "Mountain escapes": "mountain",
  "Island hopping": "tree-palm",
  "Camping trips": "tent",
  "Cultural travel": "plane",
  "Food tourism": "plane",
  "Adventure travel": "plane",
  "Hidden gems": "map",
  "World heritage sites": "landmark",
  "Travel photography": "camera",
  "Learning abroad": "languages",
  "Digital nomad life": "laptop",
  "Staycations": "plane",
  "Travel planning": "map",
  "Language exchange": "languages",
  "Nature": "trees",
  "Hiking": "backpack",
  "Camping": "tent",
  "Backpacking outdoors": "backpack",
  "Trekking": "backpack",
  "Rock climbing": "mountain",
  "Bouldering": "mountain",
  "Mountaineering": "mountain",
  "Birdwatching": "binoculars",
  "Stargazing": "rocket",
  "Gardening": "sprout",
  "Houseplants": "sprout",
  "Foraging": "sprout",
  "Fishing": "fishing-rod",
  "Kayaking": "kayak",
  "Canoeing": "kayak",
  "Sailing": "sailboat",
  "Surfing": "lab-surfboard",
  "Scuba diving": "rectangle-goggles",
  "Snorkeling": "rectangle-goggles",
  "Paddleboarding": "lab-surfboard",
  "Picnics": "trees",
  "National parks": "trees",
  "Waterfalls": "waves-horizontal",
  "Sunrise chasing": "sunrise",
  "Fitness": "heart-pulse",
  "Running": "sport-shoe",
  "Gym workouts": "dumbbell",
  "Weightlifting": "dumbbell",
  "Bodybuilding": "dumbbell",
  "CrossFit": "dumbbell",
  "Yoga": "person-standing",
  "Pilates": "person-standing",
  "Barre": "person-standing",
  "Dance fitness": "footprints",
  "Cycling": "bike",
  "Indoor cycling": "bike",
  "Swimming": "waves-ladder",
  "Walking": "sport-shoe",
  "Meditation": "person-standing",
  "Mindfulness": "person-standing",
  "Breathwork": "person-standing",
  "Cold plunging": "waves-ladder",
  "Sauna": "bath",
  "Nutrition": "chef-hat",
  "Healthy cooking": "salad",
  "Sleep wellness": "bed",
  "Self-care": "bath",
  "Mental wellness": "brain",
  "Personal growth": "brain",
  "Football": "lab-soccer-ball",
  "Basketball": "lab-basketball",
  "Volleyball": "volleyball",
  "Beach volleyball": "volleyball",
  "Baseball": "lab-baseball",
  "Softball": "lab-baseball",
  "Cricket": "lab-cricket-wicket",
  "Rugby": "lab-rugby",
  "Hockey": "lab-hockey",
  "Ice hockey": "lab-ice-hockey",
  "Field hockey": "lab-hockey",
  "Handball": "volleyball",
  "Netball": "lab-basketball",
  "Water polo": "waves-ladder",
  "Futsal": "lab-soccer-ball",
  "Ultimate frisbee": "disc",
  "Flag football": "lab-football",
  "Lacrosse": "lab-hockey",
  "Pickleball": "lab-tennis-racket",
  "Padel": "lab-tennis-racket",
  "Tennis doubles": "lab-tennis-racket",
  "Sports fandom": "trophy",
  "Fantasy sports": "trophy",
  "Stadium trips": "ticket",
  "Local leagues": "trophy",
  "Formula 1": "car",
  "Motorsports": "car",
  "Tennis": "lab-tennis-racket",
  "Badminton": "lab-tennis-racket",
  "Table tennis": "lab-tennis-racket",
  "Golf": "flag",
  "Boxing": "hand-fist",
  "Kickboxing": "hand-fist",
  "Martial arts": "hand-fist",
  "Judo": "hand-fist",
  "Karate": "hand-fist",
  "Taekwondo": "hand-fist",
  "Wrestling": "hand-fist",
  "Fencing": "swords",
  "Archery": "bow-arrow",
  "Skateboarding": "original-skateboard",
  "Roller skating": "original-skateboard",
  "Skiing": "lab-skis",
  "Snowboarding": "lab-skis",
  "Ice skating": "lab-ice-skate",
  "Horse riding": "lab-horse-head",
  "Parkour": "sport-shoe",
  "Triathlons": "sport-shoe",
  "Marathon training": "sport-shoe",
  "Adventure racing": "sport-shoe",
  "Tech": "cpu",
  "AI": "bot",
  "Coding": "code-xml",
  "Web development": "code-xml",
  "App development": "code-xml",
  "Game programming": "code-xml",
  "Cybersecurity": "shield-check",
  "Robotics": "bot",
  "Data science": "database",
  "Machine learning": "bot",
  "Cloud computing": "database",
  "Open source": "code-xml",
  "Startups": "rocket",
  "Gadgets": "cpu",
  "Smart homes": "house-plug",
  "3D printing": "cuboid",
  "Drones": "drone",
  "Space": "rocket",
  "Astronomy": "rocket",
  "Physics": "atom",
  "Biology": "dna",
  "Neuroscience": "brain",
  "Climate science": "leaf",
  "Renewable energy": "solar-panel",
  "Future technology": "headphones",
  "Study": "graduation-cap",
  "Languages": "languages",
  "History": "landmark",
  "Ancient history": "landmark",
  "Modern history": "landmark",
  "Archaeology": "landmark",
  "Geography": "map",
  "Economics": "calculator",
  "Politics": "newspaper",
  "Current events": "newspaper",
  "Sociology": "graduation-cap",
  "Anthropology": "graduation-cap",
  "Psychology": "brain",
  "Philosophy": "book-open",
  "Literature": "book-open",
  "Mathematics": "calculator",
  "Chemistry": "flask-conical",
  "Medicine": "stethoscope",
  "Law": "scale",
  "Language learning": "languages",
  "Italian language": "languages",
  "Spanish language": "languages",
  "French language": "languages",
  "German language": "languages",
  "Japanese language": "languages",
  "Nightclubs": "party-popper",
  "Dancing": "footprints",
  "Salsa dancing": "footprints",
  "Bachata": "party-popper",
  "Ballroom dancing": "footprints",
  "Live comedy": "mic-vocal",
  "Stand-up comedy": "mic-vocal",
  "Theatre": "drama",
  "Musicals": "drama",
  "Concerts": "ticket",
  "Festivals": "ticket",
  "Art galleries": "palette",
  "Museums": "landmark",
  "Bars": "beer",
  "Pubs": "beer",
  "Rooftop bars": "beer",
  "Dinner parties": "utensils",
  "House parties": "party-popper",
  "Karaoke nights": "mic-vocal",
  "Quiz nights": "dices",
  "Bowling": "lab-bowling",
  "Mini golf": "flag",
  "Farmers markets": "store",
  "Flea markets": "store",
  "Thrifting": "store",
  "Staying in": "armchair",
  "Movie marathons": "popcorn",
  "TV binges": "tv",
  "Home cooking": "chef-hat",
  "Cozy nights": "moon",
  "Reading at home": "book-open",
  "Board game nights": "dices",
  "Video game nights": "armchair",
  "Puzzle nights": "puzzle",
  "Baking days": "cake-slice",
  "Sunday mornings": "sunrise",
  "Lazy weekends": "bed",
  "Podcasts": "headphones",
  "True crime podcasts": "headphones",
  "Music podcasts": "headphones",
  "ASMR": "headphones",
  "Streaming": "radio",
  "Home cinema": "popcorn",
  "Tea time": "coffee",
  "Coffee at home": "coffee",
  "Candle collecting": "flame",
  "Scrapbooking": "notebook-pen",
  "Knitting": "spool",
  "Crocheting": "spool",
  "Jigsaw puzzles": "puzzle",
  "Fashion": "shirt",
  "Streetwear": "shirt",
  "Vintage fashion": "shirt",
  "Sustainable fashion": "recycle",
  "Luxury fashion": "shirt",
  "Sneakers": "sport-shoe",
  "Watches": "watch",
  "Jewelry": "gem",
  "Makeup": "pipette",
  "Skincare": "pipette",
  "Haircare": "scissors",
  "Nail art": "brush",
  "Fragrance": "pipette",
  "Tattoos": "pen-tool",
  "Piercings": "gem",
  "Cosplay": "venetian-mask",
  "Sewing": "spool",
  "Upcycling": "recycle",
  "Home decor": "lamp",
  "DIY projects": "hammer",
  "Furniture restoration": "hammer",
  "Minimalism": "shirt",
  "Maximalism": "shirt",
  "Vintage shopping": "store",
  "Personal style": "shirt",
  "Pets": "paw-print",
  "Dogs": "dog",
  "Cats": "cat",
  "Puppies": "dog",
  "Kittens": "cat",
  "Rescue animals": "paw-print",
  "Animal shelters": "paw-print",
  "Dog walking": "dog",
  "Dog training": "dog",
  "Cat caf\u00e9s": "cat",
  "Horses": "lab-horse-head",
  "Birds": "bird",
  "Parrots": "bird",
  "Rabbits": "rabbit",
  "Hamsters": "rat",
  "Reptiles": "turtle",
  "Aquariums": "fish",
  "Marine life": "fish",
  "Wildlife": "paw-print",
  "Wildlife photography": "camera",
  "Zoos": "paw-print",
  "Animal conservation": "paw-print",
  "Botany": "sprout",
  "Succulents": "sprout",
  "Flower arranging": "flower",
  "Business": "briefcase-business",
  "Entrepreneurship": "briefcase-business",
  "Investing": "coins",
  "Personal finance": "coins",
  "Marketing": "megaphone",
  "Branding": "palette",
  "Sales": "trending-up",
  "Product management": "presentation",
  "Project management": "presentation",
  "Leadership": "presentation",
  "Networking": "handshake",
  "Freelancing": "laptop",
  "Remote work": "laptop",
  "Coworking": "briefcase-business",
  "Career growth": "briefcase-business",
  "Mentoring": "presentation",
  "Public speaking": "mic-vocal",
  "Negotiation": "handshake",
  "E-commerce": "store",
  "Small business": "store",
  "Social enterprise": "briefcase-business",
  "Real estate": "building-2",
  "Astrology": "moon-star",
  "Creative careers": "palette",
  "Side projects": "briefcase-business",
  "Volunteering": "hand-heart",
  "Environmentalism": "recycle",
  "Sustainability": "recycle",
  "Climate action": "leaf",
  "Animal welfare": "paw-print",
  "Human rights": "megaphone",
  "Voter rights": "megaphone",
  "Community building": "users-round",
  "Local activism": "megaphone",
  "Charity work": "hand-heart",
  "Education access": "graduation-cap",
  "Mental health advocacy": "megaphone",
  "Disability inclusion": "accessibility",
  "LGBTQ+ allyship": "rainbow",
  "Gender equality": "rainbow",
  "Racial justice": "rainbow",
  "Body positivity": "sun",
  "Kindness": "hand-heart",
  "Positivity": "sun",
  "Spirituality": "moon",
  "Faith": "moon",
  "Cultural exchange": "languages",
  "Social impact": "users-round",
  "Ethical living": "recycle",
  "Zero waste": "recycle",
  "Relationships": "heart-handshake",
  "Dating": "heart-handshake",
  "Friendship": "heart-handshake",
  "New friendships": "heart-handshake",
  "Deep conversations": "messages-square",
  "Late night talks": "moon",
  "Funny conversations": "laugh",
  "Random conversations": "messages-square",
  "Life stories": "messages-square",
  "Childhood nostalgia": "hourglass",
  "Personal goals": "goal",
  "Dream sharing": "moon",
  "Travel stories": "messages-square",
  "Cultural stories": "messages-square",
  "Career talks": "messages-square",
  "Creative collaboration": "heart-handshake",
  "Accountability buddies": "heart-handshake",
  "Study buddies": "heart-handshake",
  "Workout partners": "heart-handshake",
  "Language partners": "heart-handshake",
  "Introverts": "messages-square",
  "Extroverts": "messages-square",
  "Ambiverts": "messages-square",
  "Optimism": "sun",
  "Curiosity": "lightbulb",
} as const satisfies Record<(typeof matchInterestCatalog)[number], TopicIconName>;

const key = (label: string) => label.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '');
const lookup = new Map<string, TopicIconName>(Object.entries(topicIconMap).map(([label, icon]) => [key(label), icon]));
const aliases: Record<string, TopicIconName> = {
  soccer: 'lab-soccer-ball', americanfootball: 'lab-football', cinema: 'clapperboard',
  film: 'clapperboard', deeptalks: 'messages-square', chat: 'messages-square',
  coding: 'code-xml', artificialintelligence: 'bot', reading: 'book-open',
  food: 'utensils', cooking: 'chef-hat', design: 'palette', science: 'atom',
  sports: 'trophy', gym: 'dumbbell', fitness: 'dumbbell', cricket: 'lab-cricket-wicket',
  f1: 'car', soccerball: 'lab-soccer-ball', camera: 'camera', photo: 'camera', photos: 'camera',
};
for (const [label, icon] of Object.entries(aliases)) lookup.set(label, icon);

/** Match known subjects in custom phrases; unrelated custom tags get a letter stamp. */
const subjects: ReadonlyArray<readonly [RegExp, TopicIconName]> = [
  [/\b(?:photography|photographs?|camera|photos?)\b/i, 'camera'],
  [/\b(?:american|flag) football\b/i, 'lab-football'],
  [/\b(?:football|soccer|futsal)\b/i, 'lab-soccer-ball'],
  [/\b(?:rock climbing|bouldering|mountaineering)\b/i, 'mountain'],
  [/\b(?:gaming|games|minecraft|valorant|fortnite)\b/i, 'gamepad-2'],
  [/\b(?:knitting|crocheting|sewing)\b/i, 'spool'],
  [/\b(?:basketball|netball)\b/i, 'lab-basketball'],
  [/\b(?:tennis|badminton|padel)\b/i, 'lab-tennis-racket'],
  [/\b(?:books|reading|novels)\b/i, 'book-open'],
  [/\b(?:music|songs|singing)\b/i, 'music'],
  [/\b(?:coding|programming|software)\b/i, 'code-xml'],
  [/\b(?:cooking|baking|recipes)\b/i, 'chef-hat'],
  [/\b(?:dogs|puppies)\b/i, 'dog'], [/\b(?:cats|kittens)\b/i, 'cat'],
  [/\b(?:travel|travelling|traveling)\b/i, 'plane'],
  [/\b(?:art|painting|drawing)\b/i, 'palette'],
];

export function getTopicIconName(label: string): TopicIconName | null {
  return lookup.get(key(label)) ?? subjects.find(([pattern]) => pattern.test(label))?.[1] ?? null;
}
