import React from 'react';
import { createRoot } from 'react-dom/client';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { View } from 'react-native';
import { activeScreen } from './router';
import Yap from '../../app/(tabs)/quick-chat';
import Feed from '../../app/(tabs)/feed';
import Clubs from '../../app/(tabs)/clubs';
import Messages from '../../app/(tabs)/messages';
import Profile from '../../app/(tabs)/profile';
import Tabs from '../../app/(tabs)/_layout';
import Auth from '../../app/auth/index';
import Chat from '../../app/messages/[conversationId]';
import Wallet from '../../app/wallet';
import Onboarding from '../../app/onboarding';
import Settings from '../../app/settings/account';
import Safety from '../../app/settings/safety';
import ClubCreate from '../../app/clubs/create';
import ProfileEdit from '../../app/profile/edit';
import { fonts } from '../../src/theme/tokens';
import Call from '../../app/calls/[callId]';
import Club from '../../app/clubs/[clubId]';
import Room from '../../app/clubs/room/[roomId]';
import Person from '../../app/people/[userId]';
import Post from '../../app/post/[postId]';
import Guidelines from '../../app/legal/[document]';
import QuickConversation from '../../app/quick-chat/[sessionId]';
const screens = {guidelines:Guidelines,'quick-chat':Yap,feed:Feed,clubs:Clubs,messages:Messages,profile:Profile,auth:Auth,chat:Chat,wallet:Wallet,onboarding:Onboarding,settings:Settings,safety:Safety,'club-create':ClubCreate,'profile-edit':ProfileEdit,call:Call,club:Club,room:Room,person:Person,post:Post,'quick-conversation':QuickConversation};
const Page = screens[activeScreen] || Yap;
const isTab = ['quick-chat','feed','clubs','messages','profile'].includes(activeScreen);
const artwork = new Image();
artwork.src = '/assets/conversation-night-print.png';
Promise.all([...Object.values(fonts).map(font => document.fonts.load(`16px ${font}`)), artwork.decode().catch(()=>{})]).then(() => {
  createRoot(document.getElementById('app')).render(<SafeAreaProvider initialMetrics={{frame:{x:0,y:0,width:390,height:844},insets:{top:0,left:0,right:0,bottom:0}}}><View style={{flex:1}}><Page />{isTab?<Tabs/>:null}</View></SafeAreaProvider>);
});
